@DrugDispenser_HostAddress = https://localhost:7139

POST {{DrugDispenser_HostAddress}}/Dispenser/Dispense
Content-Type: application/json

{
  "IdNumber" :
  {
    "Number":"07018941125",
    "Type": "D-Nummer"
  },
  "Code" :
  {
    "CodingSystem": "ICD-10",
    "Id": "AA.75"
  }
}

###
