@DrugDispenser_HostAddress = https://localhost:7139

### Medical Nutrition

POST {{DrugDispenser_HostAddress}}/Reimbursement/Approval
Content-Type: application/json

{
  "PatientId": "12345678",
  "RetailPrescription" :
  {
    "Name": "Proteinshake"
  }
}

### Opiate

POST {{DrugDispenser_HostAddress}}/Reimbursement/Approval
Content-Type: application/json

{
  "PatientId": "12345678",
  "DrugPrescription" :
  {
    "PrescriberId": "234567812",
    "ItemNumber": "34252"
  }
}

### Drug

POST {{DrugDispenser_HostAddress}}/Reimbursement/Approval
Content-Type: application/json

{
  "PatientId": "12345678",
  "DrugPrescription" :
  {
    "ItemNumber": "34252"
  }
}

###

POST {{DrugDispenser_HostAddress}}/Reimbursement/Approval
Content-Type: application/json

{
  "PatientId": "12345679"
}
