@DrugDispenser_HostAddress = https://localhost:7139

POST {{DrugDispenser_HostAddress}}/Dispenser/Dispense
Content-Type: application/json

{
  "PatientId": "12345678",
  "RetailPrescription" :
  {
    "Name": "Proteinshake"
  }
}

###

POST {{DrugDispenser_HostAddress}}/Dispenser/Dispense
Content-Type: application/json

{
  "PatientId": "12345678",
  "DrugPrescription" :
  {
    "PrescriberId": "234567812",
    "ItemNumber": "34252"
  }
}

###

POST {{DrugDispenser_HostAddress}}/Dispenser/Dispense
Content-Type: application/json

{
  "PatientId": "12345678",
  "DrugPrescription" :
  {
    "ItemNumber": "34252"
  }
}
